services:
  plaidify:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: gunicorn src.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000

networks:
  default:
    driver: bridge