/**
 * @plaidify/client — Official JavaScript/TypeScript SDK for Plaidify.
 */

export { Plaidify } from "./client";
export {
  PlaidifyError,
  AuthenticationError,
  NotFoundError,
  RateLimitError,
  ServerError,
} from "./errors";
export type {
  AccessJob,
  AccessJobListResult,
  PlaidifyConfig,
  HealthStatus,
  BlueprintInfo,
  BlueprintListResult,
  ConnectResult,
  MFAChallenge,
  AuthToken,
  UserProfile,
  LinkSession,
  LinkEvent,
  HostedLinkBootstrapRequest,
  HostedLinkBootstrapResponse,
  HostedLinkUrlOptions,
  WebhookRegistration,
  AgentInfo,
  AgentListResult,
  ConsentRequest,
  ConsentGrant,
  ApiKeyInfo,
  AuditEntry,
  AuditLogResult,
  AuditVerifyResult,
  WebhookDelivery,
  WebhookDeliveryResult,
  PublicTokenExchangeResult,
  RefreshScheduleResult,
  PlaidifyLinkConfig,
  PlaidifyLinkEventName,
  PlaidifyLinkEventPayload,
  PlaidifyLinkExitDetails,
  PlaidifyLinkMfaDetails,
  PlaidifyLinkSuccessMetadata,
  LinkTheme,
  PlaidifyErrorResponse,
} from "./types";
