/**
 * @plaidify/client — Official JavaScript/TypeScript SDK for Plaidify.
 */

export { Plaidify } from "./client";
export { buildHostedLinkUrl } from "./link-url";
export {
  PlaidifyError,
  AuthenticationError,
  NotFoundError,
  RateLimitError,
  ServerError,
} from "./errors";
export type {
  AccessJob,
  AccessJobListResult,
  AccessTokenInfo,
  PlaidifyConfig,
  HealthStatus,
  BlueprintInfo,
  BlueprintListResult,
  BlueprintSummary,
  ConnectResult,
  MfaSubmitResult,
  MFAChallenge,
  AuthToken,
  UserProfile,
  LinkInfo,
  LinkSession,
  LinkEvent,
  HostedLinkBootstrapRequest,
  HostedLinkBootstrapResponse,
  HostedLinkUrlOptions,
  WebhookRegistration,
  WebhookInfo,
  WebhookListResult,
  AgentInfo,
  AgentListResult,
  ConsentRequest,
  ConsentGrant,
  ConsentGrantInfo,
  ConsentListResult,
  ApiKeyCreated,
  ApiKeyInfo,
  AuditEntry,
  AuditChainError,
  AuditLogResult,
  AuditVerifyResult,
  WebhookDelivery,
  WebhookDeliveryResult,
  PublicTokenExchangeResult,
  RefreshJobInfo,
  RefreshJobListResult,
  RefreshScheduleResult,
  PlaidifyLinkConfig,
  PlaidifyLinkEventName,
  PlaidifyLinkEventPayload,
  PlaidifyLinkExitDetails,
  PlaidifyLinkMfaDetails,
  PlaidifyLinkSuccessMetadata,
  LinkTheme,
  PlaidifyErrorResponse,
} from "./types";
